import React, { Component } from 'react';
import PropTypes from "prop-types";
import { withStyles } from "@material-ui/core/styles";
import Typography from "@material-ui/core/Typography";
import Link from '@material-ui/core/link';

import ShuttleImage from '../images/shuttle.jpg';




const styles = theme => ({
    root: {
        flexGrow: 1,
    },
    image: {
        width: 128,
        height: 128,
    },
    img: {
        marginLeft: 100,
        marginTop: 20,
        display: 'block',
        maxWidth: 600,
    },
    header: {
        color: theme.palette.primary.dark,
        marginLeft: 100,
        marginBottom: 50,
        paddingTop: 100,
    },
    project: {
        marginLeft: 100,
        marginBottom: 20,
        padding: 0,
        fontWeight: 'bold',
        color: theme.palette.primary.dark,
    },
    body: {
        marginTop: 15,
        marginLeft: 100,
        marginRight: 600,
        display: 'block',
    },
});

class ProjectView extends Component{
    render(){
        const classes = this.props.classes; 

        return(
            <>
            <Typography gutterBottom variant="h2" className={classes.header}>
                    check out my work. 
            </Typography>
            <div >
                    <Typography gutterBottom variant="h5" className={classes.project}>
                        shuttle: a project tool for handweavers
                    </Typography>    
            </div>
                <div >
 
                    <Typography variant="p" className={classes.body}>
                        Shuttle takes the often scattered process of devising brand-new handweaving projects and lends digital simplicity and organization. Equipped with a calculator to determine yarn needs, photo album
                        and notepad, Shuttle is an application that makes devising, organizing, and documenting weaving projects easy.
                        
                        Shuttle uses React, Redux, Node.js, Express, PostgreSQL, Firebase & Material UI.
                    </Typography>
                    <Link
                        href="https://fierce-thicket-39020.herokuapp.com/"
                        className={classes.link}
                        target='_blank'
                        style={{ textDecoration: 'none' }}
                    >
                    <img className={classes.img} alt="complex" src={ShuttleImage} />
                    </Link>
                </div>

                <div >
                    <Typography gutterBottom variant="h5" className={classes.project}>
                        Hawaiian Islands Association for Marriage & Family Therapy (HIAMFT) Therapist Directory
                    </Typography>
                </div>
                <div >

                    <Typography variant="p" className={classes.body}>
                        The HIAMFT Therapist Directory is a web-based directory and member database. As a directory, this web application
                        features public HIAMFT therapist member listings, helping people search and find therapists that fit their
                        particular needs. Featuring Advanced Search options, autogenerated Therapist Referral Emails, and an easy-to-use
                        Google Maps feature, the HIAMFT Therapist Directory makes it easy for HIAMFT therapists to connect with new clients. 
                        Additionally, the administrative member database functionality allows HIAMFT to easily search their members,
                        manage memberships, and export their data. 
                        
                        The HIAMFT Therapist Directory was built using React, Redux, Node.js, Express, PostgreSQL, 
                        Passport, Firebase, Filesaver, NodeMailer, GoogleMaps API & React Bootstrap.

                        This project will be deployed soon! Check back to see this app up and running. 
                    </Typography>
                    <Link
                        href="https://github.com/kristenstoeckeler/Hawaii-MFT"
                        className={classes.link}
                        target='_blank'
                        style={{ textDecoration: 'none' }}
                    >
                        <img className={classes.img} alt="complex" src={ShuttleImage} />
                    </Link>
                </div>
            </>
        );
    }
}

ProjectView.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(ProjectView);

